// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pa_api.Data;

namespace pa_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191106231908_addedBooks")]
    partial class addedBooks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("pa_api.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("Date");

                    b.Property<string>("Nome");

                    b.Property<int>("livrosDoados");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("pa_api.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlunoId");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("Date");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("pa_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pa_api.Models.Livro", b =>
                {
                    b.HasOne("pa_api.Models.Aluno", "Aluno")
                        .WithMany("Livros")
                        .HasForeignKey("AlunoId");
                });
#pragma warning restore 612, 618
        }
    }
}
